config/routes.rb
Rails.application.routes.draw do
  get 'stats/index'

  resources :users
  resources :scouts do
    member do
      get :preferred_courses
      resources :records
    end
  end

  resources :preferences
  resources :records
  resources :courses
  resources :events
  resources :sessions, only: [:new, :create, :destroy]
  
  root 'static_pages#home'
  get '/help' => 'static_pages#help', as: :help
  get '/signup' => 'users#new', as: :signup
  get '/signin' => 'sessions#new', as: :signin
  get '/signout' => 'sessions#destroy', as: :signout
  get '/stats' => 'stats#index'

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :scouts, dependent: :destroy

  # Actions to perform before saving to database
  before_save { email.downcase! }
  before_save :reformat_phone
  after_save :calculate_total_cost
  before_create :create_remember_token

  # Validations on new user creation
  validates :firstname, :lastname, presence: true
  validates :firstname, :lastname, length: {
    maximum: 40,
    too_long: "First or last name cannot be more than 40 characters"
  }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: { case_sensitive: false }, 
            format: { with: VALID_EMAIL_REGEX }

  VALID_PHONE_REGEX = /\d{3}.*\d{3}.*\d{4}/
  validates :phone, presence: true, format: { with: VALID_PHONE_REGEX }

  # Password for users
  has_secure_password 
  validates :password, length: { minimum: 6 }, on: :create
  validates :password_confirmation, presence: true, on: :update,
            :unless => lambda{ |user| user.password.blank? }


  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def calculate_total_cost
    total_cost = 0

    if self.admin
      Scout.all.each do |scout|
        total_cost += scout.cost unless scout.cost.nil?
      end
    else
      self.scouts.each do |scout|
        total_cost += scout.cost unless scout.cost.nil?
      end
    end
    
    update_columns(total_cost: total_cost)
  end


  def lunch_cards
    lunch_cards = 0

    self.scouts.each do |scout|
      lunch_cards += 1 if scout.scout_lunch
      lunch_cards += scout.additional_lunch if scout.additional_lunch
    end

    return lunch_cards
  end

  def scout_count
    return Scout.where(user: self.id).count
  end

  def patch_count
    patches = 0

    self.scouts.each do |scout|
      patches += 1 if scout.patch
    end

    return patches
  end

  private

    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end

    def reformat_phone
      phone_match = /(\d{3}).*(\d{3}).*(\d{4})/.match(self.phone.to_s)
      self.phone = "(#{phone_match[1]}) #{phone_match[2]}-#{phone_match[3]}"
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :signed_in_user, only: [:index, :edit, :update, :destroy, :correct_user]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: [:destroy]
  before_action :already_signed_in, only: [:new]

  def index
    @users = User.reorder("lastname asc").page(params[:page]).per_page(40)
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to MBU Online!"
      redirect_to @user
    else
      render :new
    end
  end

  def update
    user = User.find_by(email: current_user.email).try(:authenticate, params[:current_password])

    if params[:admin]
      flash.now[:danger] = "Unable to change admin privileges"
      render :edit
    end

    if (user || current_user.admin?) && @user.update(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      flash.now[:danger] = "Incorrect Current Password" unless user
      sign_in @user
      render :edit
    end
  end

  def destroy
    @user.destroy
    flash[:warning] = "#{@user.firstname} was deleted"
    redirect_to users_url
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:firstname, :lastname, :troop, :district, :council, :phone,
                                   :email, :password, :password_confirmation, :admin)
    end

    def correct_user
      unless current_user? @user or current_user.admin?
        redirect_to root_url
        flash[:danger] = "Sorry, you aren't authorized to perform that action"
      end
    end

    def already_signed_in
      if signed_in?
        flash[:info] = "You are already signed in"
        redirect_to root_url
      end
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="container">
  <%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
      <%= render 'shared/user_error_messages' %>
    <% end %>

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Your Information</h3>
      </div>
      <div class="panel-body">
        <div class="form-group col-md-6">
          <%= f.label :firstname, "First Name" %>
          <%= f.text_field :firstname, class: "form-control", placeholder: "Enter your first name" %>
        </div>
        <div class="form-group col-md-6">
          <%= f.label :lastname, "Last Name" %>
          <%= f.text_field :lastname, class: "form-control", placeholder: "Enter your last name" %>
        </div>

        <div class="form-group col-md-6">
          <%= f.label :email %>
          <%= f.email_field :email, class: "form-control", placeholder: "you@example.com" %>
        </div>
        <div class="form-group col-md-6">
          <%= f.label :phone, "Phone Number" %>
          <%= f.telephone_field :phone, class: "form-control", placeholder: "(555) 555-5555" %>
        </div>

        <div class="form-group col-md-6">
          <%= f.label :troop %>
          <%= f.number_field :troop, class: "form-control", placeholder: "Troop number" %>
        </div>
        <div class="form-group col-md-6">
          <%= f.label :district %>
          <%= f.text_field :district, class: "form-control", placeholder: "District" %>
        </div>

        <div class="form-group col-md-6">
          <%= f.label :council %>
          <%= f.text_field :council, class: "form-control", placeholder: "Council" %>
        </div>
      </div>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Change Password (Optional)</h3>
      </div>
      <div class="panel-body">
        <div class="form-group col-md-6">
          <%= f.label :password %>
          <%= f.password_field :password, class: "form-control", placeholder: "New Password (Optional)" %>
        </div>
        <div class="form-group col-md-6">
          <%= f.label :password_confirmation, "Confirmation" %>
          <%= f.password_field :password_confirmation, class: "form-control", placeholder: "New Password Confirmation" %>
        </div>
      </div>
    </div>

    <% if current_user.admin? %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Make this user an Administrator</h3>
        </div>
        <div class="panel-body">
          <div class="form-group col-md-6">
            <%= f.label :admin, "Administrator?" %>
            <%= f.check_box :admin, class: "form-control" %>
          </div>
        </div>
      </div>
    <% end %>

    <div class="col-md-6 col-md-offset-3">
      <%= f.label "Enter Current Password to Save Changes" %>
      <%= password_field_tag :current_password, params[:current_password],
          class: "form-control", placeholder: "Current password"%>
    </div>
    <div class="actions col-md-6 col-md-offset-3"></div>
    <div class="actions col-md-6 col-md-offset-3">
      <%= f.submit "Save changes", class: "btn btn-med btn-default center-block btn-block" %>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Update User") %>

<div class="page-header">
  <h1>Update Profile </h1>
</div>

<%= render 'form' %>

app/views/users/index.html.erb
<% provide(:title, "All Users") %>
<div class="page-header">
  <h1>Users of MBU Online</h1>
</div> 

<%= will_paginate %>

<div class="table-responsive">
  <table class="table table-hover table-striped">
    <thead>
      <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Troop</th>
        <th>District</th>
        <th>Council</th>
        <th>Phone</th>
        <th>Email</th>
        <% if current_user.admin? %>
          <th>Cost of Attendance</th>
          <th>Total Lunch Cards</th>
          <th>Total Registerd Scouts</th>
          <th>Patches</th>
        <% end %>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.firstname %></td>
          <td><%= user.lastname %></td>
          <td><%= user.troop %></td>
          <td><%= user.district %></td>
          <td><%= user.council %></td>
          <td><%= user.phone %></td>
          <td><%= user.email %></td>
          <% if current_user.admin? %>
            <td><%= number_to_currency user.total_cost %></td>
            <td><%= user.lunch_cards %></td>
            <td><%= user.scout_count %></td>
            <td><%= user.patch_count %></td>
          <% end %>
          <td><%= link_to 'Details', user %></td>
          <% if current_user.admin? %>
            <td><%= link_to "Edit", edit_user_path(user) %></td>
          <% end %>
          <td><% if current_user.admin? && !current_user?(user) %>
              <%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' } %>
              <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, "Sign up") %>
<div class="page-header">
  <h2>Sign up</h2>
</div>

<div class="span6 offset3">

  <div class="panel panel-default">
    
    <div class="panel-heading">
        <p>Sign up for a new account with MBU Online. All fields are required</p>
    </div>
    <div class="panel-body">  
    <%= form_for(@user) do |f| %>
      <%= render 'shared/user_error_messages' %>

      <div class="form-group col-md-6">
        <%= f.label :firstname, "First Name" %>
        <%= f.text_field :firstname, class: "form-control", placeholder: "Enter your first name" %>
      </div>
      <div class="form-group col-md-6">
        <%= f.label :lastname, "Last Name" %>
        <%= f.text_field :lastname, class: "form-control", placeholder: "Enter your last name" %>
      </div>

      <div class="form-group col-md-6">  
        <%= f.label :email %>
        <%= f.email_field :email, class: "form-control", placeholder: "you@example.com" %>
      </div>
      <div class="form-group col-md-6">
        <%= f.label :phone, "Phone Number" %>
        <%= f.telephone_field :phone, class: "form-control", placeholder: "(555) 555-5555" %>
      </div>

      <div class="form-group col-md-6">
        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
      </div>
      <div class="form-group col-md-6">
        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Password Confirmation" %>
      </div>
      <div class="form-group col-md-4 col-md-offset-4 actions">
        <%= f.submit "Create my account", class: "btn btn-default center-block" %>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<% provide(:title, "#{@user.firstname} #{@user.lastname}") %>

<div class="page-header">
  <% if current_user?(@user) %>
    <h1>Your Details</h1>
  <% else %>
    <h1>Details about <%= @user.firstname %></h1>
  <% end %>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <% if current_user?(@user) %>
      <h3 class="panel-title">Your information 
      <%= link_to 'Edit', edit_user_path(@user), class: "btn btn-xs btn-default pull-right" %> </h3>
    <% else %>
      <h3 class="panel-title"><%= @user.firstname %>'s information</h3>
    <% end %>
  </div>
  <div class="panel-body">
    <p>
      <strong>First Name:</strong>
      <%= @user.firstname %>
    </p>

    <p>
      <strong>Last Name:</strong>
      <%= @user.lastname %>
    </p>

    <p>
      <strong>Troop:</strong>
      <%= @user.troop %>
    </p>

    <p>
      <strong>District:</strong>
      <%= @user.district %>
    </p>

    <p>
      <strong>Council:</strong>
      <%= @user.council %>
    </p>

    <p>
      <strong>Phone:</strong>
      <%= @user.phone %>
    </p>

    <p>
      <strong>Email:</strong>
      <%= @user.email %>
    </p>

  </div>
</div>

<% if current_user.admin?%>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">
      <% if current_user.admin? %>
        <%= "#{@user.firstname}'s Scouts (Troop #{@user.troop})" %>
      <% else %>
        Your scouts
      <% end %> 
      <%= link_to 'Add a scout', new_scout_path, class: "btn btn-xs btn-default pull-right" %> </h3>
    </div>
    <%= render 'shared/scouts_list' %>
  </div>
<% end %>

<% if current_user?(@user) || current_user.admin?%>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">
      <% if current_user.admin? %>
        <%= "#{@user.firstname} #{@user.lastname}'s Roster (Troop #{@user.troop})" %>
      <% else %>
        Your Roster
      <% end %> 
    </div>
    <h5 class="text-center">
      <strong>Total cost of attendance:</strong>
      <%= number_to_currency @user.total_cost %> 
    </h5>
    <h5 class="text-center">
      <strong>Total registered scouts:</strong>
      <% event = Event.where(current: true).last %>
      <% scout_count = 0 %>
      <% @user.scouts.each { |scout| scout_count += 1 if scout.records_for? event} %>
      <%= scout_count %>      
    </h5>
    <%= render 'shared/scouts_roster' %>
  </div>
<% end %>

<div class="btn-group">
  <%= link_to 'List of Scoutmasters', users_path, class: "btn btn-md btn-default" %>
</div>