config/routes.rb
Rails.application.routes.draw do
  get 'stats/index'

  resources :users
  resources :scouts do
    member do
      get :preferred_courses
      resources :records
    end
  end

  resources :preferences
  resources :records
  resources :courses
  resources :events
  resources :sessions, only: [:new, :create, :destroy]
  
  root 'static_pages#home'
  get '/help' => 'static_pages#help', as: :help
  get '/signup' => 'users#new', as: :signup
  get '/signin' => 'sessions#new', as: :signin
  get '/signout' => 'sessions#destroy', as: :signout
  get '/stats' => 'stats#index'

end

app/views/shared/_all_scouts_list.html.erb
<% scout_list = Scout.all.reorder("troop asc, lastname asc").page(params[:page]).per_page(40) if current_user.admin? %>

<%= will_paginate scout_list %>

<div class="table-responsive">
  <table class="table table-hover table-striped">
    
    <thead>
      <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Age</th>
        <th>Troop</th>
        <th>Emergency Contact</th>
        <th>Notes</th>
        <th>Preferred Courses</th>
        <th>Assigned Courses</th>
        <th>Cost of Attendance</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    
    <tbody>
      <% event = Event.where(current: true).last %>
      <% scout_list.each do |scout| %>
        <tr>
          <td><%= scout.firstname %></td>
          <td><%= scout.lastname %></td>
          <td><%= scout.age %></td>
          <td><%= scout.troop %></td>
          <td>
            <div class="dropdown">
              <button class="btn btn-default btn-xs dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown">
                Name: <%= scout.emergency_name %>
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                <li role="presentation"><a role="menuitem" tabindex="-1" href="#">
                  Phone: <%= scout.emergency_phone %></a></li>
                <li role="presentation"><a role="menuitem" tabindex="-1" href="#">
                  Relationship: <%= scout.emergency_relation %></a></li>
              </ul>
            </div>
          </td>
          <td>
            <% if !scout.notes.nil? && !scout.notes.empty? %>
              <div class="dropdown">
                <button class="btn btn-default btn-xs dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown">
                  <%= scout.notes[0..20] %>
                  <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu2">
                  <li role="presentation"><a role="menuitem" tabindex="-1" href="#"><%= scout.notes %></a></li>
                </ul>
              <% end %>
            </div>
          </td>
          <td>

            <% preferences = scout.preferences.where(event: event).order("priority asc") %>
            <% if !preferences.empty? %>
              <div class="dropdown">
                <button class="btn btn-default btn-xs dropdown-toggle" type="button" id="dropdownMenu3" data-toggle="dropdown">
                  <%= "#{preferences.first.course.name}" %>
                  <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu3">
                  <% preferences.each_with_index do |preference, index| %>
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">
                    <%= "#{preference.priority.ordinalize} Priority:" unless preference.priority.nil? %>
                    <%= link_to preference.course.name, preference.course %></a></li>
                    <% unless index == preferences.size - 1 %>
                      <li class="divider">
                    <% end %>
                      </li>
                  <% end %>
                </ul>
              </div>
            <% end %>
          </td>
          <td>
            <% records = scout.records.where(event: event).order("period asc") %>
            <% if !records.empty? %>
              <div class="dropdown">
                <button class="btn btn-default btn-xs dropdown-toggle" type="button" id="dropdownMenu3" data-toggle="dropdown">
                  <%= "#{records.first.course.name}" %>
                  <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu3">
                  <% records.each_with_index do |record, index| %>
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">
                    <%= "#{record.period.ordinalize} Period:" unless record.period.nil? %>
                    <%= link_to record.course.name, record.course %></a></li>
                    <% unless index == records.size - 1 %>
                      <li class="divider">
                    <% end %>
                      </li>
                  <% end %>
                </ul>
              </div>
            <% end %>
          </td>
          <td><%= number_to_currency scout.cost %>
          <td><%= link_to 'Details', scout %></td>
          <td><%= link_to 'Edit Scout', edit_scout_path(scout) %></td>
          <td><%= link_to 'Delete', scout, method: :delete, data: { confirm: 'Are you sure? This action can\'t be reversed'} %></td>
        </tr> 
      <% end %>  
    </tbody>
  
  </table>
</div>

<%= will_paginate scout_list %>

app/views/shared/_assigned_courses.html.erb
<% scout = Scout.find_by(id: params[:id]) %>
<% if !scout.nil? && !scout.records.empty? %>
  <div class="table-responsive">
    <table class="table table-hover table-striped">
      
      <thead>
        <tr>
          <th>Event</th>
          <th>Course Name</th>
          <th>Description</th>
          <th>Period</th>
          <th>Completed Requirements</th>
          <th colspan="2"></th>
        </tr>
      </thead>
      
      <tbody>
        <%= hidden_field_tag :scout_id, scout.id %>
        <% scout.records.order("event_id desc, period asc").each do |record| %>
          <tr>
            <td><%= "#{record.event.semester} #{record.event.year}" %></td>
            <td><%= link_to record.course.name %></td>
            <td><%= record.course.description %></td>
            <td><%= record.period %></td>
            <td><%= record.completion %></td>
            <td>
              <% if current_user.admin? %>
                <%= link_to 'Delete', record, method: :delete, data: 
                { confirm: 'Are you sure? You cannot undo this action'} %>
               <% end %>
            </td>
            <td>
              <% if current_user.admin? %>
                <%= link_to 'Edit Completion Record', edit_record_path(record) %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    
    </table>
  </div>
<% end %>

app/views/shared/_course_error_messages.html.erb
<% if @course.errors.any? %>
  <p class="alert alert-danger">
    <% @course.errors.full_messages.each do |msg| %>
      <%= msg %></li></br>
    <% end %>
  </p>
<% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
  </div>
  <p class="alert alert-danger">
    <% @user.errors.full_messages.each do |msg| %>
      <%= msg %></li></br>
    <% end %>
  </p>
<% end %>

app/views/shared/_preferred_courses.html.erb
<% scout = Scout.find_by(id: params[:id]) %>
<% if !scout.nil? && !scout.preferred_courses.empty? %>
  <div class="table-responsive">
    <table class="table table-hover table-striped">
      
      <thead>
        <tr>
          <th>Course Name</th>
          <th>Description</th>
          <th>Priority</th>
          <th>Event</th>
          <th colspan="2"></th>
        </tr>
      </thead>
      
      <tbody>
        <% event = Event.where(current: true).last %>
        <%= hidden_field_tag :scout_id, scout.id %>
        <% scout.preferences.where(event: event).order("priority asc").each do |preference| %>
          <tr>
            <td><%= link_to preference.course.name %></td>
            <td><%= preference.course.description %></td>
            <td><%= preference.priority %></td>
            <td><%= "#{preference.event.semester} #{preference.event.year}" %></td>
            <td><%= link_to 'Edit Priority', edit_preference_path(preference) %></td>
            <td>
              <%= link_to 'Delete', preference, method: :delete, data: 
              { confirm: 'Are you sure? You cannot undo this action'} %>
            </td>
          </tr>
        <% end %>
      </tbody>
    
    </table>
  </div>
<% end %>

app/views/shared/_scout_error_messages.html.erb
<% if @scout.errors.any? %>
  <p class="alert alert-danger">
    <% @scout.errors.full_messages.each do |msg| %>
      <%= msg %></li></br>
    <% end %>
  </p>
<% end %>

app/views/shared/_scouts_list.html.erb
<% scout_list = Scout.where(user_id: params[:id]).reorder("troop asc, lastname asc").page(params[:page]).per_page(40) if current_user.admin? %>
<% scout_list = current_user.scouts.reorder("lastname asc").page(params[:page]).per_page(40) if !current_user.admin?%>

<%= will_paginate scout_list %>

<div class="table-responsive">
  <table class="table table-hover table-striped">
    
    <thead>
      <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Age</th>
        <th>Troop</th>
        <th>Emergency Contact</th>
        <th>Notes</th>
        <th>Preferred Courses</th>
        <th>Assigned Courses</th>
        <th>Shirt Size</th>
        <th>Cost of Attendance</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    
    <tbody>
      <% event = Event.where(current: true).last %>
      <% scout_list.each do |scout| %>
        <tr>
          <td><%= scout.firstname %></td>
          <td><%= scout.lastname %></td>
          <td><%= scout.age %></td>
          <td><%= scout.troop %></td>
          <td>
            <div class="dropdown">
              <button class="btn btn-default btn-xs dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown">
                Name: <%= scout.emergency_name %>
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                <li role="presentation"><a role="menuitem" tabindex="-1" href="#">
                  Phone: <%= scout.emergency_phone %></a></li>
                <li role="presentation"><a role="menuitem" tabindex="-1" href="#">
                  Relationship: <%= scout.emergency_relation %></a></li>
              </ul>
            </div>
          </td>
          <td>
            <% if !scout.notes.nil? && !scout.notes.empty? %>
              <div class="dropdown">
                <button class="btn btn-default btn-xs dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown">
                  <%= scout.notes[0..20] %>
                  <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu2">
                  <li role="presentation"><a role="menuitem" tabindex="-1" href="#"><%= scout.notes %></a></li>
                </ul>
              <% end %>
            </div>
          </td>
          <td>
            <% preferences = scout.preferences.where(event: event).order("priority asc") %>
            <% if !preferences.empty? %>
              <div class="dropdown">
                <button class="btn btn-default btn-xs dropdown-toggle" type="button" id="dropdownMenu3" data-toggle="dropdown">
                  <%= "#{preferences.first.course.name}" %>
                  <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu3">
                  <% preferences.each_with_index do |preference, index| %>
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">
                    <%= "#{preference.priority.ordinalize} Priority:" unless preference.priority.nil? %>
                    <%= link_to preference.course.name, preference.course %></a></li>
                    <% unless index == preferences.size - 1 %>
                      <li class="divider">
                    <% end %>
                      </li>
                  <% end %>
                </ul>
              </div>
            <% end %>
          </td>
          <td>
            <% records = scout.records.where(event: event).order("period asc") %>
            <% if !records.empty? %>
              <div class="dropdown">
                <button class="btn btn-default btn-xs dropdown-toggle" type="button" id="dropdownMenu3" data-toggle="dropdown">
                  <%= "#{records.first.course.name}" %>
                  <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu3">
                  <% records.each_with_index do |record, index| %>
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">
                    <%= "#{record.period.ordinalize} Period:" unless record.period.nil? %>
                    <%= link_to record.course.name, record.course %></a></li>
                    <% unless index == records.size - 1 %>
                      <li class="divider">
                    <% end %>
                      </li>
                  <% end %>
                </ul>
              </div>
            <% end %>
          </td>
          <td><%= scout.shirt_size if scout.shirt %></td>
          <td><%= number_to_currency scout.cost %>
          <td><%= link_to 'Details', scout %></td>
          <td><%= link_to 'Edit Scout', edit_scout_path(scout) %></td>
          <td><%= link_to 'Delete', scout, method: :delete, data: { confirm: 'Are you sure? This action can\'t be reversed'} %></td>
        </tr> 
      <% end %>  
    </tbody>
  
  </table>
</div>

<%= will_paginate scout_list %>

app/views/shared/_scouts_roster.html.erb
<div class="table-responsive">
  <table class="table table-hover table-striped">

    <thead>
      <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Troop</th>
        <th>Scout Lunch Card</th>
        <th>Additional Lunches</th>
        <th>T-Shirt</th>
        <th>Period 1</th>
        <th>Period 2</th>
        <th>Period 3</th>
        <th>Total Cost</th>
      </tr>
    </thead>

    <tbody>
      <% event = Event.where(current: true).last %>
      <% scout_list = Scout.where(user_id: params[:id]) if current_user.admin? %>
      <% scout_list = current_user.scouts if !current_user.admin?%>
      <% scout_list.each do |scout| %>
        <% next unless scout.records_for? event %>
        <% first_period = scout.records.where(period: 1, event: event).first.course if scout.records.where(period: 1, event: event).first %>
        <% second_period = scout.records.where(period: 2, event: event).first.course if scout.records.where(period: 2, event: event).first %>
        <% third_period = scout.records.where(period: 3, event: event).first.course if scout.records.where(period: 3, event: event).first %>
        <% scout_lunch = 0 %>
        <% scout_lunch += 1 if scout.scout_lunch %>
        <% additional_lunch = 0 %>
        <% additional_lunch += scout.additional_lunch if scout.additional_lunch %>
        <tr>
          <td><%= scout.firstname %></td>
          <td><%= scout.lastname %></td>
          <td><%= scout.troop %></td>
          <td><%= scout_lunch %></td>
          <td><%= additional_lunch %></td>
          <td><%= scout.shirt ? "Yes, #{scout.shirt_size}" : "No" %></td>
          <td><%= "#{first_period.name}, #{first_period.room}" if first_period %></td>
          <td><%= "#{second_period.name}, #{second_period.room}" if second_period %></td>
          <td><%= "#{third_period.name}, #{third_period.room}" if third_period %></td>
          <td><%= scout.cost %></td>
        </tr>
      <% end %>
    </tbody>

  </table>
</div>

app/views/shared/_user_error_messages.html.erb
<% if @user.errors.any? %>
  <p class="alert alert-danger">
    <% @user.errors.full_messages.each do |msg| %>
      <%= msg %></li></br>
    <% end %>
  </p>
<% end %>