config/routes.rb
Rails.application.routes.draw do
  get 'stats/index'

  resources :users
  resources :scouts do
    member do
      get :preferred_courses
      resources :records
    end
  end

  resources :preferences
  resources :records
  resources :courses
  resources :events
  resources :sessions, only: [:new, :create, :destroy]
  
  root 'static_pages#home'
  get '/help' => 'static_pages#help', as: :help
  get '/signup' => 'users#new', as: :signup
  get '/signin' => 'sessions#new', as: :signin
  get '/signout' => 'sessions#destroy', as: :signout
  get '/stats' => 'stats#index'

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand">
        <%= link_to "MBU Online", root_path, id: "MBU" %>
      </div>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right"> 
        <% if signed_in? %>
           <% if current_user.admin? %>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown">
                <%= "Administration" %>
                <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to "Events", events_path %></li>
                <li><%= link_to "Stats", stats_path %></li>
                <li><%= link_to "Scoutmasters", users_path %></li>
                <li><%= link_to "All Scouts", scouts_path %></li>
              </ul>
            </li>
          <% end %>
         <li><%= link_to "Courses", courses_path %></li>
 
          <% if !current_user.admin? %>
            <li><%= link_to "Your Scouts", scouts_path %></li>
          <% end %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.firstname %>
              <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li><%= link_to "Sign out", signout_path %>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign in", signin_path %></li>
        <% end %>
      </ul>
    </div>
  
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<meta name="viewport" content="width=device-width, initial-scale=1">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %> 
    </div>
    <div class="container">
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>

</html>